---
version: "3.7"

x-common: &common
  stdin_open: true # docker run -i
  tty: true        # docker run -t
  networks:
    - k8s-internal

services:
  api: &api
    <<: *common
    build: k8s-api
    container_name: k8s-api
    depends_on:
      - async
      - sql
    env_file:
      - .envs/api.env
      - .envs/redis.env
      - .envs/sql.env
    volumes:
      - ./k8s-api:/code

  async:
    <<: *common
    build: k8s-async
    container_name: k8s-async
    env_file:
      - .envs/graph.env
      - .envs/redis.env
      - .envs/sql.env
    volumes:
      - ./k8s-async:/code

  front:
    <<: *common
    build: k8s-front
    container_name: k8s-front
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./k8s-front:/code/
    tty: false

  graph:
    <<: *common
    build: k8s-graph
    container_name: k8s-graph
    networks:
      - k8s-internal
    volumes:
      - k8s-graph:/data/

  nginx:
    <<: *common
    build: k8s-nginx
    container_name: k8s-nginx
    depends_on:
      - api
      - front
      - graph
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:8000/core/alive/"]
      interval: 1m
      timeout: 1s
      retries: 1
      start_period: 10s
    ports:
      - "443:443"    # front
      - "7474:7474"  # graph
      - "7687:7687"  # graph
      - "8000:8000"  # api
    volumes:
      - ./k8s-nginx/dev.conf:/etc/nginx/conf.d/dev.conf

  redis:
    <<: *common
    build: k8s-redis
    container_name: k8s-redis
    env_file:
      - .envs/redis.env
    volumes:
      - k8s-redis:/data/

  sql:
    <<: *common
    build: k8s-sql
    container_name: k8s-sql
    env_file:
      - .envs/sql.env
    volumes:
      - k8s-sql:/var/lib/postgresql/data/

#  worker:
#    <<: *api
#    command: |
#      celery
#      --app api.celery
#      worker
#      --beat
#      --schedule /tmp/celery-beat
#      --loglevel WARNING
#    container_name: k8s-worker
#    environment:
#      - COLUMNS=80
#    healthcheck:
#      test: ["CMD", "celery", "--app", "api.celery", "inspect", "ping"]
#      interval: 1m
#      retries: 3
#      start_period: 10s

networks:
  k8s-internal:

volumes:
  k8s-sql:
  k8s-graph:
  k8s-redis:
