apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPbHdYaEFFOGdvQXRKZzUzM05iClNISThYSWRzWDMwOFQxR0FqUnlSU1BsTmVmN1FkTDVhbU9ja2RYSlRxb3hETTl2bTVoUm45VFoxdVErdmtucTEKbWMrVGlHY3h6Q3pnLzdhbjNHb1Nrays0Ri9mbWZwS3pBVXFKSStZckhhMFpDcXluNldQY0xWd3dQR0VqZ2IxdAozSkNnb0I5MW5GTXBQaW9CQUUycjEvWlE4TzVmaVoybWpQUVYxeXlvdmxJTG02VU9TTWo1bHpsOGZhSm15bFJmClZ5c3FqNFNpaVc5Y2lEaTlXQ1BsTXIrU2Q2c0w1eWwwS1QxYnZpMFQyVHBTNDlEMUJ3VGRxTTBlQnk2Vk90MFEKMUlaOGtxWlFISjUxZHRlSmEyWmpvZm1wY2cxRGdpcHp4M3V5WGIrRVZ3UHl5Tk9EajlhWEQ4Tkp1UDRHa0U4Rwp3cjhDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFXRWxMMEg0NUI2RThRZGZNcmtEV3dqSktICjRkUGQ5Q2NzQXZxQ0pQTmNvN09HbFYvVUxHUE5WcEZHZWUzajRIbGJvZ1dRbUxBdTVVMUJBMXcydm0vak5SWngKWGpvUHI2NXpvNzdzanZwSzRLU1JYREV5cW56SW0rbUlzS05uMGpvekdxOURoTzFybk9lN1hOOVZwUDVySVpBegoyNXhlT21KRHU0QnZYd0dnaFU5WjJRbTIxcFRVdEkzTWxubnl0bTVETVVOODFzUFpGK2todWJXYVRoeDdKOXpNCkE5QnpScVY1TVRweS9ncnQ0WkczU0ZuNXlFZitzWVNkaW5EQXVWVklvVE5taFQ3SzRzVE1JdzVUT1hHQkE2NDgKb0pheStrQnVERGxNRjNFcTVsMTM0N1Vqdy9EK202N2l4ODdnYjU0eFRkaWtsNE13Y0xLK3NFUVRmOW9sCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth

